// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3N-1SlYIY5ofSIwbXcwyWeTIJtq75ejA',
    appId: '1:1016629578388:web:10dd2bf55dabb53cc9c281',
    messagingSenderId: '1016629578388',
    projectId: 'chatapptute-3334f',
    authDomain: 'chatapptute-3334f.firebaseapp.com',
    storageBucket: 'chatapptute-3334f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGrjl2p5WTUPlJxpA5lNIUBlcIyICovCo',
    appId: '1:1016629578388:android:da534a3d02c4028cc9c281',
    messagingSenderId: '1016629578388',
    projectId: 'chatapptute-3334f',
    storageBucket: 'chatapptute-3334f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNrIVB8rNb3mr3fi8l3H7SJI4_8UUPs58',
    appId: '1:1016629578388:ios:5c2379c3c5909158c9c281',
    messagingSenderId: '1016629578388',
    projectId: 'chatapptute-3334f',
    storageBucket: 'chatapptute-3334f.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNrIVB8rNb3mr3fi8l3H7SJI4_8UUPs58',
    appId: '1:1016629578388:ios:cdae27ba3b319270c9c281',
    messagingSenderId: '1016629578388',
    projectId: 'chatapptute-3334f',
    storageBucket: 'chatapptute-3334f.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
